#!/usr/bin/env bash

ARGS=(--allow-net --allow-env --allow-read --unstable)

if grep -q "DEBUG=1" .env; then
    deno test "${ARGS[@]}" test/ &&
        deno run "${ARGS[@]}" src/main.ts
else
    deno run "${ARGS[@]}" src/main.ts
fi
