name: Test Deno Module

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno_version: [1.2.0]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno_version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno_version }}
      # - name: Format check Deno Module
      #   run: deno fmt --check
      - name: Lint Deno Module
        run: deno lint --unstable
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'github'
          mysql root password: 'github'
          mysql user: 'github'
          mysql password: 'github'
      - run: |
          echo 'DEBUG=2' > .env
          echo 'PORT=8080' >> .env
          echo 'DBUser="github"' >> .env
          echo 'DBPassword="github"' >> .env
          echo 'DBName="github"' >> .env
          echo 'DBHost="localhost"' >> .env
      - name: Test Deno Module
        run: ./run
